version: '2'
services:
  app:
    image: node:9.11.2-alpine
    tty: true
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - queue
  queue:
    image: rabbitmq:3.7.5
    tty: true
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
